export const song_list = [
  { title: "Error", author: "Error" },
  { title: "Waltz in E flat”Grande Valse Brillante”Op.18", author: "Frédéric François Chopin" },
  { title: "Moments Musicaux", author: "Franz Peter Schubert" },
  { title: "Bagatelle “Für Elise” WoO.59", author: "Ludwig van Beethoven" },
  { title: "The Preludes Op. 28 No.15", author: "Frédéric François Chopin" },
  { title: "Turkish March", author: "Ludwig van Beethoven" },
  { title: "Blumenlied Op.39", author: "Gustav Lange" },
  { title: "Nocturne", author: "Frédéric François Chopin" },
  { title: "Spinnerlied Op.14 No.4", author: "Albert Ellmenreich" },
  { title: "String Quartet in F major Op.3 No.5 Serenade", author: "Franz Peter Schubert" },
  { title: "Wiegenlied", author: "Johannes Brahms" },
  { title: "Solvejgs Lied", author: "Edvard Hagerup Grieg" },
  { title: "Anitras Dans", author: "Edvard Hagerup Grieg" },
  { title: "Traumerei", author: "Robert Alexander Schumann" },
  { title: "Menuett No.2 in G maj", author: "Ludwig van Beethoven" },
  { title: "Aida Fernando Corena", author: "Giuseppe Fortunino Francesco Verdi" },
  { title: "William Tell Overture", author: "Gioachino Antonio Rossini" },
  { title: "Carmen", author: "Georges Bizet" },
  { title: "Andante religioso", author: "Jules Emile Frédéric Massenet" },
  { title: "Tannhauser Overture", author: "Wilhelm Richard Wagner" },
  { title: "La Traviata Brindisi", author: "Giuseppe Fortunino Francesco Verdi" },
  { title: "Plaisir d’Amour", author: "Jean Paul Egide Martini" },
  { title: "Ellens Gesang III Op.52-6 D.839", author: "Franz Peter Schubert" },
  { title: "Die Meistersinger von Nurnberg Prelude", author: "Wilhelm Richard Wagner" },
  { title: "Orpheé aux Enfers Overture", author: "Jacques Offenbach" },
  { title: "L’arlesienne Suite No.2 Farandole", author: "Georges Bizet" },
  { title: "Overture No.3 BWV.1068 Air on a G string", author: "Johann Sebastian Bach" },
  { title: "Peer Gynt Suite No.1 Op.46 Morgenstemning", author: "Edvard Hagerup Grieg" },
  { title: "Le carnaval des animaux Le Cygne", author: "Charles Camille Saint-Saëns" },
  { title: "Greensleeves", author: "unknown" },
  { title: "3 Gymnopedies No.1", author: "Erik Alfred Leslie Satie" },
  { title: "Sinfonie Nr.9 d moll Op.125 4.Satz An die Freude", author: "Ludwig van Beethoven" },
  { title: "The Nutcracker Suite Op.71a No.8 Waltz of the Flowers", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "Swan Lake Op.20 No.9 Finale", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "Water Music in D major HWV 349 No.11 Alla Hornpipe", author: "Georg Friedrich Händel" },
  { title: "Ombra mai fü HWV 40", author: "Georg Friedrich Händel" },
  { title: "Estudiantina Op.191", author: "Émile Waldteufel" },
  { title: "Sonate für Klavier Nr.48 C dur Op.30-1 Mov.1", author: "Franz Joseph Haydn" },
  { title: "Sonate für Klavier Nr.15 C dur K.545 Mov.1", author: "Wolfgang Amadeus Mozart" },
  { title: "Andante C dur", author: "Franz Joseph Haydn" },
  { title: "Alpengluhen Op.193", author: "Theodor Oesten" },
  { title: "Children’s Album Op.39-18 Air de Danse napolitaine", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "Children’s Album Op.39-9 Valse", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "Les Contes d’Hoffmann Barcarolle", author: "Jacques Offenbach" },
  { title: "Rosamunde Prinzessin von Zypern Op.26 D797 Intermezzo No.3", author: "Franz Peter Schubert" },
  { title: "Gianni Schicchi O mio babbino caro", author: "Giacomo Antonio Domenico Michele Secondo Maria Puccini" },
  { title: "Dichterliebe Op.48-1 Im wunderschönen Monat", author: "Robert Alexander Schumann" },
  { title: "Le Nozze di Figaro ＫＶ492 Voi che sapete", author: "Wolfgang Amadeus Mozart" },
  { title: "Rigoletto La donna È mobile", author: "Giuseppe Fortunino Francesco Verd" },
  { title: "The Planets Op.32 Jupiter, the Bringer of Jollity", author: "Gustav Holst" },
  { title: "Amazing Grace", author: "unknown" },
  { title: "Fantasiestücke Op.12-2 Aufschwung", author: "Robert Alexander Schumann" },
  { title: "Fantasiestücke Op.12-7 Traumes Wirren", author: "Robert Alexander Schumann" },
  { title: "Lieder ohne Worte Op.19-3 Jägerlied", author: "Jakob Ludwig Felix Mendelssohn Bartholdy" },
  { title: "Suite HWV 430 Air mit Variationen Harmonious Blacksmith", author: "Georg Friedrich Händel" },
  { title: "Farewell To The Piano WoO.62", author: "Ludwig van Beethoven" },
  { title: "Le Coucou", author: "Louis-Claude Daquin" },
  { title: "Waves of the Danube", author: "Iosif Ivanovici" },
  { title: "Waltzes No.6 Op.64-1 Des dur Valse du Petit Chien", author: "Frédéric François Chopin" },
  { title: "Schwanengesang No.1 Op.72-4 D.957-4 Ständchen", author: "Franz Peter Schubert" },
  { title: "Má Vlast Moldau", author: "Bedřich Smetana" },
  { title: "Album für die Jugend Op.68-10 Frohlicher Landmann", author: "Robert Alexander Schumann" },
  { title: "Doll’s Dreaming and Awakening Op.202", author: "Theodor Oesten" },
  { title: "25 Etudes faciles et progressives, conposées et doigtées expressément pour l’étendue des petites mains Op.100-2 Arabesque", author: "Johann Friedrich Franz Burgmuller" },
  { title: "Stimmen aus der Kinderwelt 12 leichte Vortragsstück Op.78-3 Heideröslein", author: "Gustav Lange" },
  { title: "25 Etudes faciles et progressives, conposées et doigtées expressément pour l’étendue des petites mains Op.100-20 Tarentelle", author: "Johann Friedrich Franz Burgmuller" },
  { title: "The Nutcracker Suite Op.71a No.2 March", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "Ballade g moll Op.23", author: "Frédéric François Chopin" },
  { title: "12 Etudes E dur Op.10-3", author: "Frédéric François Chopin" },
  { title: "Kanon und Gigue D dur für drei Violinen und Basso Continuo Kanon", author: "Johann Pachelbel" },
  { title: "Herz und Mund und Tat und Leben BWV147-6 Wohl mir, daß ich Jesum habe", author: "Johann Sebastian Bach" },
  { title: "Messiah HWV.56 23.Hallelujah", author: "Georg Friedrich Händel" },
  { title: "Préludes 1 La fille aux cheveux de lin", author: "Claude Achille Debussy" },
  { title: "Pavane pour une infante défunte", author: "Joseph-Maurice Ravel" },
  { title: "8 Humoresky Op.101-7 B.187 Ges dur", author: "Antonín Leopold Dvořák" },
  { title: "Sicilienne Op.78", author: "Gabriel Urbain Fauré" },
  { title: "Salut d’amour Op.12", author: "Sir Edward William Elgar" },
  { title: "Violinkonzert e moll Op.64 1.Satz", author: "Jakob Ludwig Felix Mendelssohn Bartholdy" },
  { title: "Concerti a 4 e 5 Il cimento dell’armonia e dell’inventione Op.8 Le quattro stagioni Concerti Nr.1E dur RV.269 La Primavera", author: "Antonio Lucio Vivaldi" },
  { title: "Eine kleine Nachtmusik G dur K.525 1.Satz", author: "Wolfgang Amadeus Mozart" },
  { title: "Symphonie Nr.40 g moll KV.550 1.Satz", author: "Wolfgang Amadeus Mozart" },
  { title: "Symphony No.9 in E minor Op.95 B.178 From the New World Mov.2 Goin’ Home", author: "Antonín Leopold Dvořák" },
  { title: "An der schönen blauen Donau Op.314", author: "Johann Strauß II" },
  { title: "Radetzky-Marsch Op.228", author: "Johann Strauß I" },
  { title: "Toccata und Fuge d moll BWV565", author: "Johann Sebastian Bach" },
  { title: "Tableaux d’une exposition Promenade", author: "Modest Petrovich Mussorgsky" },
  { title: "Pomp and Circumstance Op.39 No.1", author: "Sir Edward William Elgar" },
  { title: "Impromptu cis moll Op.66", author: "Frédéric François Chopin" },
  { title: "Scherzo b moll Op.31", author: "Frédéric François Chopin" },
  { title: "12 Etudes c moll Op.10-12", author: "Frédéric François Chopin" },
  { title: "Impromptus D 935 Op.142-3 B dur", author: "Franz Peter Schubert" },
  { title: "Rondo D dur K.485", author: "Wolfgang Amadeus Mozart" },
  { title: "Französische Suiten Nr.5 G dur BWV 816 Gavotte", author: "Johann Sebastian Bach" },
  { title: "Sechs Gesänge Op.34-2 Auf Flügeln des Gesanges", author: "Jakob Ludwig Felix Mendelssohn Bartholdy" },
  { title: "Csikos Post", author: "Hermann Necke" },
  { title: "12 Variationen über ein französisches Lied ‘Ah,vous dirai-je, maman’ C dur K.265 K6.300e", author: "Wolfgang Amadeus Mozart" },
  { title: "Lieder ohne Worte Heft 5 Op.62-6 Frühlingslied", author: "Jakob Ludwig Felix Mendelssohn Bartholdy" },
  { title: "Les Patineurs Op.183", author: "Émile Waldteufel" },
  { title: "Sonate für Klavier Nr.8 c moll Pathetique Op.13 2.Satz", author: "Ludwig van Beethoven" },
  { title: "3 Valses No.7 Op.64-2 cis moll", author: "Frédéric François Chopin" },
  { title: "Sonate für Klavier Nr.11 A dur K.331 K6.300i Mov.1", author: "Wolfgang Amadeus Mozart" },
  { title: "Violinromanze Nr.2 F dur Op.50", author: "Ludwig van Beethoven" },
  { title: "Polonaisen 3 Militaire A dur Op.40-1", author: "Frédéric François Chopin" },
  { title: "Carmen Habanera", author: "Georges Bizet" },
  { title: "Ein Sommernachtstraum Wedding March Op.61-9", author: "Jakob Ludwig Felix Mendelssohn Bartholdy" },
  { title: "Beautiful Dreamer", author: "Stephen Collins Foster" },
  { title: "Toy Symphony", author: "Johann Georg Leopold Mozart" },
  { title: "Liebestraume 3 Notturnos S.541 R.211 As dur", author: "Franz Liszt" },
  { title: "Walkürenritt Ride of the Valkyries", author: "Wilhelm Richard Wagner" },
  { title: "Sonate für Klavier und Violine Nr.5 F dur “Frühling” Op.24", author: "Ludwig van Beethoven" },
  { title: "L’Arlésienne Menuett", author: "Georges Bizet" },
  { title: "The Bridal Chorus from the opera Lohengrin", author: "Wilhelm Richard Wagner" },
  { title: "Madama Butterfly Un bel dì, vedremo", author: "Giacomo Antonio Domenico Michele Secondo MariaPuccini" },
  { title: "Concerto for piano and orchestra No.1 Op.23 Mov.1", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "Symphony No.1 Op.68 C major", author: "Johannes Brahms" },
  { title: "L’amico Fritz", author: "Pietro Mascagnit" },
  { title: "Pièces de clavecin avec une méthode sur la mécanique des doigts “Tambourin”", author: "Jean-Philippe Rameau" },
  { title: "Symphony No.4 A major Op.90", author: "Jakob Ludwig Felix Mendelssohn Bartholdy" },
  { title: "Sonatine Op.36-4 F dur 1.Satz", author: "Muzio Filippo Vincenzo Francesco Saverio Clementi" },
  { title: "Son tutta duolo", author: "Alessandro Scarlatti" },
  { title: "What a Friend We Have in Jesus", author: "Charles Crozat Converse" },
  { title: "Sonatine Op.36-5 G dur", author: "Muzio Filippo Vincenzo Francesco Saverio Clementi" },
  { title: "Impromptus D.935 Op.142 B dur", author: "Franz Peter Schubert" },
  { title: "Tre giorni son che Nina", author: "Giovanni Battista Pergolesi" },
  { title: "Rhapsody in Blue", author: "George Gershwin" },
  { title: "Sonatine Op.20-3 F dur", author: "Daniel Friedrich Rudolph Kuhlau" },
  { title: "La traviata Parigi o cara noi lasciaremo", author: "Giuseppe Fortunino Francesco Verdi" },
  { title: "Corrente", author: "Girolamo Frescobaldi" },
  { title: "Sonate für Klavier Nr.27 e moll Op.90 1.Satz", author: "Ludwig van Beethoven" },
  { title: "Ungarische Rhapsodie S.244 Nr.2 cis moll", author: "Franz Liszt" },
  { title: "The nutcracker suite Op.71a “Trepak”", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "Sonate für Klavier Nｒ.7 D dur Op.10-3 3.Satz", author: "Ludwig van Beethoven" },
  { title: "Musikalisches Zeitvertreib Op.22 Schlag-aria", author: "Johann Valentin Rathgeber" },
  { title: "Sonate für Klavier Nr.15 C dur K.545 3.Satz", author: "Wolfgang Amadeus Mozart" },
  { title: "Sonate für Klavier Nｒ.3 C dur Op.2-3 4.Satz", author: "Ludwig van Beethoven" },
  { title: "Peer Gynt Suite No.1 Op.46 Åses Død", author: "Edvard Hagerup Grieg" },
  { title: "Concerto for Flute & Harp K299 Mov.1", author: "Wolfgang Amadeus Mozart" },
  { title: "Sonate für Klavier Nr.19 g moll Op.49-1 2.Satz", author: "Ludwig van Beethoven" },
  { title: "Horn Concerto No.1 D major", author: "Wolfgang Amadeus Mozart" },
  { title: "Les saisons 12 Morceaux caracteristiques Op.37bis No.6 “Barcarolle”", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "Symphony No.7 A major Op.92 Mov.4", author: "Ludwig van Beethoven" },
  { title: "Rondo brillante “Aufforderung zum Tanz” Op.65", author: "Carl Maria Friedrich Ernst von Weber" },
  { title: "Star vicino", author: "Salvator Rosa" },
  { title: "Flute Concerto La notte RV.439 Op.10 No.2", author: "Antonio Lucio Vivaldi" },
  { title: "Sonatine Op.36-1", author: "Muzio Filippo Vincenzo Francesco Saverio Clementi" },
  { title: "Se florindo e fedele", author: "Alessandro Scarlatti" },
  { title: "5 Mazurka No.5 Op.7-1 B dur", author: "Frédéric François Chopin" },
  { title: "Vittoria, mio core!", author: "Giacomo Carissimi" },
  { title: "Sonatine Op.20-1 C dur", author: "Daniel Friedrich Rudolph Kuhlau" },
  { title: "Caro mio ben", author: "Giuseppe Giordani" },
  { title: "Adagio", author: "Heinrich Joseph Barmann" },
  { title: "Massa’s in De Cold Ground", author: "Stephen Collins Foster" },
  { title: "Allegretto No.4", author: "Louis A. Saint-Jacome" },
  { title: "La cinquantaine", author: "Gabriel Prosper Marie" },
  { title: "Le Coucou", author: "Louis-Claude Daquin" },
  { title: "Gavotte", author: "Christoph Graupner" },
  { title: "La Gemissante Rondeau", author: "Jean-François Dandrieu" },
  { title: "Pièces de clavecin avec une méthode sur la mécanique des doigts “La joyeuse”", author: "Jean-Philippe Rameau" },
  { title: "Sonatine Op.20 Nr.1", author: "Johann Ladislaus Dussek" },
  { title: "String Quartet No.73 F dur Op.74-2 Hob.III:73 “The Military Quartet”", author: "Franz Joseph Haydn" },
  { title: "Rigaudon", author: "Georg Böhm" },
  { title: "Sonate für Klavier Nｒ.5 c moll Op.10-1 3.Satz", author: "Ludwig van Beethoven" },
  { title: "Die schöne Müllerin Op.25 D.795 Wohin?", author: "Franz Peter Schubert" },
  { title: "Fanfare", author: "Johann Philipp Kirnberger" },
  { title: "A musical snuffbox Op.32", author: "Lyadov, Anatoly Konstantinovich" },
  { title: "Sonate für Klavier Nr.20 G dur Op.49-2 1.Satz", author: "Ludwig van Beethoven" },
  { title: "Symphony No.7 A major Op.92 Mov.1", author: "Ludwig van Beethoven" },
  { title: "Divertimento No.1 in B flat major “Chorale St. Antoni” Hob.II:46", author: "Franz Joseph Haydn" },
  { title: "Light Cavalry Overture", author: "Franz von Suppe" },
  { title: "Sonate für Klavier Nｒ.5 c moll Op.10-1 1.Satz", author: "Ludwig van Beethoven" },
  { title: "Sonate für Klavier Nr.8 c moll “Pathetique” Op.13 1.Satz", author: "Ludwig van Beethoven" },
  { title: "Musical Parnassus Euterpe Suite No.6 Chaconne", author: "Johann Caspar Ferdinand Fischer" },
  { title: "Sonata K.531 L.430", author: "Domenico Scarlatti" },
  { title: "Sonatine Op.36-3 C dur", author: "Muzio Filippo Vincenzo Francesco Saverio Clementi" },
  { title: "Winterreise D.911 Op.89 Gute Nacht", author: "Franz Peter Schubert" },
  { title: "Hunting", author: "Louis A. Saint-Jacome" },
  { title: "The little nigar", author: "Claude Achille Debussy" },
  { title: "La sonnambula", author: "Vincenzo Bellini" },
  { title: "Rondo D dur K.485", author: "Wolfgang Amadeus Mozart" },
  { title: "Pizzicato Polka", author: "Johann Baptist Strauß, Josef Strauß" },
  { title: "Symphony No.6 “Pateticheskaya” Op.74", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "Rondo grazioso No.25", author: "Louis A. Saint-Jacome" },
  { title: "Sonate für Klavier Nｒ.6 F dur Op.10-2 1.Satz", author: "Ludwig van Beethoven" },
  { title: "24 Caprices for Solo Violin No.24 Quasi Presto", author: "Niccolò Paganinit" },
  { title: "Sonate für Klavier Nr.26 Es dur “Lebewohl” Op.81a 1.Satz", author: "Ludwig van Beethoven" },
  { title: "Lento cantabile grandioso No.7", author: "Louis A. Saint-Jacome" },
  { title: "Annen-Polka Op.117", author: "Johann Baptist Strauß" },
  { title: "Sonate für Klavier Nｒ.3 C dur Op.2-3 1.Satz", author: "Ludwig van Beethoven" },
  { title: "Sonate für Klavier Nr.4 Es dur Op.7 4.Satz", author: "Ludwig van Beethoven" },
  { title: "Petere es a farkas Op.67", author: "Prokof’ev, Sergei Sergeevich" },
  { title: "Menuet en Rondeau C major", author: "Jean-Philippe Rameau" },
  { title: "Winterreise D.911 Op.89 Frühlingstraum", author: "Franz Peter Schubert" },
  { title: "Le Coq d’Or Hymn to the Sun", author: "Nikolai Andreyevich Rimsky-Korsakov" },
  { title: "Simple aveu Op.25", author: "Francis Thomé" },
  { title: "Romance", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "Deux Mélodies Op.3-1 F dur", author: "Rubinstein Anton" },
  { title: "2 Marches caracteristiques D.968 B.886 Op.121 C dur", author: "Franz Peter Schubert" },
  { title: "Die Lorelei", author: "Phillipp Friedrich Silcher" },
  { title: "Music for the Royal Fireworks HWV 351 II bourrée", author: "Georg Friedrich Händel" },
  { title: "La jolie fille de Perth sérénade", author: "Georges Bizet" },
  { title: "Gigue", author: "Jean-Baptiste de Lully" },
  { title: "Hornpipe G minor", author: "Henry Purcell" },
  { title: "Pièces de clavecin avec une méthode sur la mécanique des doigts “Premier rigaudon”", author: "Jean-Philippe Rameau" },
  { title: "Quartet for 2 Violins, Viola and Violoncello D major 3 Nocturne", author: "Alexander Porfir’evich Borodin" },
  { title: "Sonate für Klavier Nr.4 Es dur Op.7 1.Satz", author: "Ludwig van Beethoven" },
  { title: "Peer Gynt Suite Nr.2 Op.55 I dovregubbens hall", author: "Edvard Hagerup Grieg" },
  { title: "Die Fledermaus Overture Op.367", author: "Johann Baptist Strauß" },
  { title: "Gavotte F major", author: "Jean Paul Egide Martini" },
  { title: "Goldberg-Variationen Aria BWV 988", author: "Johann Sebastian Bach" },
  { title: "Suite No.6 G major La Coquette R.130", author: "Georg Muffat" },
  { title: "La Molinara Nel cor pìù non mi sento", author: "Giovanni Paisiello" },
  { title: "Sonate für Klavier Nr.8 c moll “Pathetique” Op.13 3.Satz", author: "Ludwig van Beethoven" },
  { title: "Sleeping Beauty Op.66", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "Menuett G dur K.1", author: "Wolfgang Amadeus Mozart" },
  { title: "19 Polish Songs Op.74 No.1 Zyczenie", author: "Frédéric François Chopin" },
  { title: "Ungarische Tänze Nr.1 WoO.1", author: "Johannes Brahms" },
  { title: "Valse No.10 Op.69-2 h moll", author: "Frédéric François Chopin" },
  { title: "Valse No.14 Op.posth e moll", author: "Frédéric François Chopin" },
  { title: "Menuett", author: "Johann Mattheson" },
  { title: "Parthenia Pavana and galiardo,The Earle of Salisbury", author: "William Byrd" },
  { title: "Così fan tutte, ossia La scuola degli amanti K.588", author: "Frédéric Françoiss Chopin" },
  { title: "Dimmi,amor", author: "Arcangelo del Leuto" },
  { title: "Fantaisie “Wandererfantasie” D.760 Op.15", author: "Franz Peter Schubert" },
  { title: "7 Marionnettes No.2 Poupee valsante", author: "Eduard Poldini" },
  { title: "Ungariche Tänze WoO.1 Nr.5 fis moll", author: "Johannes Brahms" },
  { title: "Ein Sommernachtstraum Notturno Op.61-7", author: "Jakob Ludwig Felix Mendelssohn Bartholdy" },
  { title: "Etude No.23", author: "Louis A. Saint-Jacome" },
  { title: "Don Giovanni K.527", author: "Wolfgang Amadeus Mozart" },
  { title: "Le nouve musichi Amarilli", author: "Giulio Caccini" },
  { title: "Symphony No.1 Op.68 C major", author: "Johannes Brahms" },
  { title: "Scheherazade Op.35", author: "Rimsky-Korsakov, Nikolai Andreevich" },
  { title: "Andantino No.4", author: "Louis A. Saint-Jacome" },
  { title: "Gigue", author: "Georg Philipp Telemann" },
  { title: "Love in Idleness", author: "Allan Macbeth" },
  { title: "Nocturne No.5 H.37", author: "John Field" },
  { title: "2 Polonaises Op.26-1 cis moll", author: "Frédéric François Chopin" },
  { title: "Suite No.4 B flat major Cantabile R.115", author: "Gottlieb Muffat" },
  { title: "The nutcracker suite Op.71a “Dance of the reed-flutes”", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "Sonate für Klavier Nr.48 C dur Hob.XVI:35 Op.30-1 Mov.1", author: "Franz Joseph Haydn" },
  { title: "L’arlesienne Suite No.1 Prelude", author: "Georges Bizet" },
  { title: "Nocturne “La séparation” G. vi, 204", author: "Mikhail Ivanovich Glinka" },
  { title: "Sonate für Klavier Nr.11 B dur Op.22 1.Satz", author: "Ludwig van Beethoven" },
  { title: "Symphony No.8 Op.88 Mov.3 Allegretto grazioso", author: "Antonín Leopold Dvořák" },
  { title: "Lieder ohne Worte Heft 1 Op.19 “Regrets”", author: "Jakob Ludwig Felix Mendelssohn Bartholdy" },
  { title: "Musicalische Vorstellung einiger biblischer Historien in sechs Sonaten auf dem Claviere zu spielen “Der Todtkranke und wieder gesunde Hiskias”", author: "Johann Kuhnau" },
  { title: "Madrigale", author: "Achille Simonetti" },
  { title: "Londonderry Air", author: "Louis A. Saint-Jacome" },
  { title: "Sonate für Klavier Nr.20 G dur Op.49-2 2.Satz", author: "Ludwig van Beethoven" },
  { title: "Sonate für Klavier Nｒ.7 D dur Op.10-3 1.Satz", author: "Ludwig van Beethoven" },
  { title: "Konzert für Klavier und Orchester Nr.5 Es dur Op.73 1.Satz", author: "Ludwig van Beethoven" },
  { title: "Symphony No.39 E flat major K.543", author: "Wolfgang Amadeus Mozart" },
  { title: "Konzert für Klavier und Orchester Nr.21 C dur K.467 Mov.1", author: "Wolfgang Amadeus Mozart" },
  { title: "Flute Quartet No.1 D major K.285", author: "Wolfgang Amadeus Mozart" },
  { title: "Easy duet", author: "Louis A. Saint-Jacome" },
  { title: "Frühling", author: "Wilhelm Friedemann Bach" },
  { title: "Adagio G minor", author: "Tomaso Giovanni Albinoni" },
  { title: "Der Tod und Das Mädchen Op.7-3 D.531 2.Satz", author: "Franz Peter Schubert" },
  { title: "Sonate für Klavier Nr.48 C dur Hob.XVI:35 Op.30-1 Mov.3 Finale", author: "Franz Joseph Haydn" },
  { title: "Winterreise D.911 Op.89 Der Lindenbaum", author: "Franz Peter Schubert" },
  { title: "Französische Suiten Nr.5 G dur BWV 816 Gavotte", author: "Johann Sebastian Bach" },
  { title: "Cantabile D dur Op.17 MS.109", author: "Niccolò Paganini" },
  { title: "Winterreise D.911 Op.89 Wasserflut", author: "Franz Peter Schubert" },
  { title: "Sonate für Klavier Nr.12 As dur Op.26 2.Satz", author: "Ludwig van Beethoven" },
  { title: "The nutcracker suite Op.71a “Miniature overture”", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "12 Etudes Op.25-9 “Butterfly” Ges dur", author: "Frédéric François Chopin" },
  { title: "Deux Mazurkas Caracterstiques “2.Le Menetrier” Op.19-2", author: "Henryk Wieniawski" },
  { title: "Grande valse brillante Es dur Op.18 CT207", author: "Frédéric François Chopin" },
  { title: "Woodland Sketches Op.51-1 To a Wild Rose", author: "Edward Alexander MacDowell" },
  { title: "Menuet in A Minor", author: "Johann Philipp Krieger" },
  { title: "Fuga C dur", author: "Johann Pachelbel" },
  { title: "Siciliana", author: "Henry Purcell" },
  { title: "16 Walzer Op.39-15 As dur", author: "Johannes Brahms" },
  { title: "Serenata Rimpianto", author: "Enrico Toselli" },
  { title: "Fantasia La Traviata", author: "Giuseppe Fortunino Francesco Verdi" },
  { title: "Cavalleria Rusticana Intermezzo", author: "Pietro Mascagni" },
  { title: "Siciliana", author: "Maria Theresa von Paradies" },
  { title: "Serenade No.1 in A major", author: "Franz Drdla" },
  { title: "Nocturne No.21 c moll KK.IVb/8 CT128", author: "Frédéric François Chopin" },
  { title: "3 Nocturnes Es dur Op.9-2", author: "Frédéric François Chopin" },
  { title: "Violin Concerto in D major Op.35", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "Symphonie No.3 F Dur Op.90 Mov.2", author: "Johannes Brahms" },
  { title: "Akademische Festouvertüre Op.80", author: "Johannes Brahms" },
  { title: "Sonate für Klavier Nr.8 c moll “Pathetique” Op.13 2.Satz", author: "Ludwig van Beethoven" },
  { title: "La Bohème “Quando me n’vo soletta per la via”", author: "Giacomo Antonio Domenico Michele Secondo MariaPuccini" },
  { title: "Sento nel core", author: "Alessandro Scarlatti" },
  { title: "Caro laccio", author: "Francesco Gasparini" },
  { title: "Six Sonatinas Op.55-1 2.Satz C dur", author: "Friedrich Kuhlau" },
  { title: "6 Progressive Sonatinas Op.36-1 3.Satz C major", author: "Muzio Filippo Vincenzo Francesco Saverio Clementi" },
  { title: "6 Progressive Sonatinas Op.36-6 2.Satz D major", author: "Muzio Filippo Vincenzo Francesco Saverio Clementi" },
  { title: "The Nutcracker Op.71 No.14 Pas de Deux, Variations, and Coda", author: "Pyotr Il’yich Tchaikovsky" },
  { title: "Carmen Prelude", author: "Georges Bizet" },
  { title: "La Gioconda Danza dell’ Ore", author: "Amilcare Ponchielli" },
  { title: "La traviata Prelude", author: "Giuseppe Fortunino Francesco Verdi" },
  { title: "Silvery Waves", author: "Addison Pinneo Wyman" },
  { title: "Das zweiten Notenbuch der Anna Magdalena Bach Menuett G Dur BWVAnh.114", author: "Johann Sebastian Bach" },
  { title: "Turandot Nessun dorma", author: "Giacomo Antonio Domenico Michele Secondo MariaPuccini" },
  { title: "Judas Maccabaeus HWV63 See the conquering hero comes", author: "Georg Friedrich Händel" },
  { title: "Etude No.1", author: "Louis A. Saint-Jacome" },
  { title: "Etude No.6", author: "Louis A. Saint-Jacome" },
  { title: "Celebrate duet No.4", author: "Louis A. Saint-Jacome" },
  { title: "Suite”Shiki ” No.1 Hana", author: "Rentaro Taki" },
];


export const song_data_sorted_by_author = song_list.map(
  (data, no) => ({
    ...data,
    no,
    family: data.author.split(" ").slice(-1)[0]
  })).sort((a, b) => a.family > b.family ? 1 : a.family < b.family ? -1 : a.title > b.title ? 1 : -1)
